import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <div className='navbar w-full bg-lime-500 h-[2rem]'>navbar</div>
        {children}</body>
      <div className='navbar w-full bg-lime-500 h-[2rem]'>footer</div>
    </html>
  )
}
